export const CHANGE_USERNAME = "boilerplate/Home/CHANGE_USERNAME";
export const FETCH_USER_LIST = "[USER] FETCH USER LIST";
export const FETCH_USER_LIST_FAILED = "[USER] FETCH USER LIST FAILED";
export const FETCH_USER_LIST_SUCCESSFUL = "[USER] FETCH USER LIST SUCCESSFUL";
export const SET_ACTIVE_USERS = "[USER] FETCH ACTIVE USERS";
export const FETCH_USER = "[USER] SET USER";
export const FETCH_USER_SUCCESS = "[USER] SET USER SUCCESSFUL";

